version: '3.8'
name: sunflower-sms
services:
  db:
    image: mysql:lts
    container_name: mysql-data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sfdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - sunflower_data:/var/lib/mysql
    networks:
      - sf-network

networks:
  sf-network:
    driver: bridge

volumes:
  sunflower_data: