version: '3.8'
name: sunflower-sms
services:
  db:
    image: mysql:lts
    container_name: mysql-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sfdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - sunflower-data:/var/lib/mysql
    networks:
      - sf-network

networks:
  sf-network:
    name: sf-network
    driver: bridge

volumes:
  sunflower-data:
    name: sunflower-data